set nocompatible

filetype off 
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

set number
set smarttab
set softtabstop=2
set smartindent
set tabstop=2
set autoindent

let mapleader=','
let g:ctrlp_map='<c-t>'

nmap <c-p> :bnext<cr>
nmap <c-o> :bprev<cr>

syntax on
syntax enable
set background=dark
colorscheme mango
