set nocompatible

filetype off 
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

set number
set background=dark
set smarttab
set autoindent
set softtabstop=2
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set hlsearch
set showmode

let mapleader=','
let g:ctrlp_map='<c-t>'

nmap <c-p> :bnext<cr>
nmap <c-o> :bprev<cr>
nmap <leader><space> :set hlsearch!<cr>

syntax on
syntax enable
colorscheme mango
